import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Box } from '@mui/system'
import { Typography } from '@mui/material'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Box sx={{display:"flex",flexWrap:"wrap",justifyContent:"center",textAlign:"center",flexDirection:"column",alignItems:"center",marginBottom:"30px"}}>
          <Typography variant='h1' sx={{fontSize:"30px",color:"GrayText"}}>Wear the code with Codeclouths.com</Typography>
          <Typography variant='p' sx={{color:"gray",marginBottom:"5px"}}>Wear whatever you want? what do you want? you want code? so why not wear the code?</Typography>
          <Typography variant='p' sx={{color:"gray",marginBottom:"5px"}}>Wear whatever you want? what do you want? you want code? so why not wear the code?</Typography>
          <Typography variant='p' sx={{color:"gray",marginBottom:"5px"}}>Wear whatever you want? what do you want? you want code? so why not wear the code?</Typography>
        </Box>
    </>
  )
}
